sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 025911
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t6JHUCsQaBCdZtqYTu5
    access-key-secret:
    bucket-name: sky-mizore
  redis:
    host: localhost
    port: 6379
    database: 10
  wechat:
    appid: wx827cd5618183312a
    secret:

