sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 025911
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tSmmNpRR3p3MAGyeepj
    access-key-secret: 19tegsRToEMYKIkc2wxiEa0te1M2jM
    bucket-name: sky-mizore